# --------------------
# Core spring settings
# --------------------

spring:
  application:
    name: user-job-service
  profiles:
    active: local
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: create

# ---------------
# Server settings
# ---------------
server:
  port: 8080

# --------------------
# Spring doc settings
# --------------------
springdoc:
  api-docs:
    resolve-schema-properties: true